use std::{
    fs::OpenOptions,
    io::Write,
    path::{Path, PathBuf},
};

use git2::{Commit, Delta, DiffFindOptions, Repository};

/// Tries to find the root (not a submodule) of the git repository by traversing up the directory tree.
pub fn find_root(path: &Path) -> Option<PathBuf> {
    match Repository::discover(path) {
        Ok(repo) => {
            let workdir = repo.workdir().unwrap().to_path_buf();
            if let Some(parent) = workdir.parent() {
                if let Ok(_) = Repository::discover(parent) {
                    return find_root(parent);
                }
            }
            Some(workdir)
        }
        Err(_) => None,
    }
}

pub fn get_patch(
    parent: &git2::Commit,
    commit: &git2::Commit,
    repo: &Repository,
) -> anyhow::Result<String> {
    let mut diff = repo.diff_tree_to_tree(Some(&parent.tree()?), Some(&commit.tree()?), None)?;
    let mut find_opts = DiffFindOptions::new();
    find_opts.renames(true);
    find_opts.copies(true);
    diff.find_similar(Some(&mut find_opts))?;

    let stats = diff.stats()?.to_buf(git2::DiffStatsFormat::FULL, 80)?;

    let mut patch = String::new();

    patch.push_str(&format!("From {} Mon Sep 17 00:00:00 2001\n", commit.id()));
    patch.push_str(&format!(
        "From: {} <{}>\n",
        commit.author().name().unwrap(),  // TODO: do not unwrap
        commit.author().email().unwrap(), // TODO: do not unwrap
    ));
    patch.push_str(&format!("Date: {}\n", commit.author().when().seconds())); // TODO: RFC2822
    patch.push_str(&format!(
        "Subject: [PATCH] {}\n",
        commit.summary().unwrap_or("") // this is not the actual subject line format generated by `git format-patch`, but it's sufficient for our use case
    ));

    // TODO: add custom headers

    patch.push_str("\n");

    if let Some(body) = commit.body() {
        patch.push_str(body);
    }

    patch.push_str("\n---\n");

    patch.push_str(std::str::from_utf8(&stats)?);
    for delta in diff.deltas() {
        match delta.status() {
            Delta::Added => {
                let path = delta.new_file().path().unwrap().to_str().unwrap();
                let mode = delta.new_file().mode();
                patch.push_str(&format!(" create mode {:o} {}\n", i32::from(mode), path));
            }
            Delta::Deleted => {
                let path = delta.old_file().path().unwrap().to_str().unwrap();
                let mode = delta.old_file().mode();
                patch.push_str(&format!(" delete mode {:o} {}\n", i32::from(mode), path));
            }
            _ => {} // TODO: handle other types of changes (e.g. modified, renamed, copied)
        }
    }
    patch.push_str("\n");

    diff.print(git2::DiffFormat::Patch, |_, _, line| {
        let origin = line.origin();
        match origin {
            ' ' | '+' | '-' => {
                patch.push(origin);
            }
            _ => (),
        };

        let Ok(content) = std::str::from_utf8(line.content()) else {
            return false;
        };
        patch.push_str(content);
        true
    })?;
    Ok(patch)
}

pub fn write_patch_to_file(
    parent: &Commit,
    commit: &Commit,
    repo: &Repository,
    path: &Path,
) -> anyhow::Result<()> {
    let patch = get_patch(parent, commit, repo)?;
    let mut file = OpenOptions::new()
        .write(true)
        .create(true)
        .truncate(true)
        .open(path)?;

    file.write_all(patch.as_bytes())?;
    Ok(())
}
