use std::{collections::HashMap, fs::OpenOptions, io::Write, path::Path, sync::LazyLock};

use anyhow::Context;
use base64::{Engine, prelude::BASE64_STANDARD};
use git2::{Commit, Delta, DiffFindOptions, DiffStatsFormat, Repository};
use regex::Regex;

use crate::utils::sig_utils::SignatureData;

const X_GIT_PATCHER_AUTHOR: &str = "X-Git-Patcher-Author";
const X_GIT_PATCHER_COMMITTER: &str = "X-Git-Patcher-Committer";
const X_GIT_PATCHER_COMMIT_MESSAGE: &str = "X-Git-Patcher-Commit-Message";
pub fn get_patch(parent: &Commit, commit: &Commit, repo: &Repository) -> anyhow::Result<String> {
    let mut diff = repo.diff_tree_to_tree(Some(&parent.tree()?), Some(&commit.tree()?), None)?;
    let mut find_opts = DiffFindOptions::new();
    find_opts.renames(true);
    find_opts.copies(true);
    diff.find_similar(Some(&mut find_opts))?;

    let stats = diff.stats()?.to_buf(DiffStatsFormat::FULL, 80)?;

    let mut patch = String::new();

    patch.push_str(&format!("From {} Mon Sep 17 00:00:00 2001\n", commit.id()));
    patch.push_str(&format!(
        "From: {} <{}>\n",
        commit.author().name().unwrap(),  // TODO: do not unwrap
        commit.author().email().unwrap(), // TODO: do not unwrap
    ));
    let datetime = git_time_to_chrono_datetime(commit.author().when())
        .with_context(|| "Failed to convert git time to chrono datetime")?;
    patch.push_str(&format!("Date: {}\n", datetime.to_rfc2822()));
    patch.push_str(&format!(
        "Subject: [PATCH] {}\n",
        commit.summary().unwrap_or("") // this is not the actual subject line format generated by `git format-patch`, but it's sufficient for our use case
    ));

    // custom headers
    patch.push_str(&format!(
        "{X_GIT_PATCHER_AUTHOR}: {}\n",
        SignatureData::from(commit.author())
    ));
    patch.push_str(&format!(
        "{X_GIT_PATCHER_COMMITTER}: {}\n",
        SignatureData::from(commit.committer())
    ));
    patch.push_str(&format!(
        "{X_GIT_PATCHER_COMMIT_MESSAGE}: {}\n",
        BASE64_STANDARD.encode(commit.message_raw_bytes())
    ));

    patch.push_str("\n");

    if let Some(body) = commit.body() {
        patch.push_str(body);
    }

    patch.push_str("\n---\n");

    patch.push_str(std::str::from_utf8(&stats)?);
    for delta in diff.deltas() {
        match delta.status() {
            Delta::Added => {
                let path = delta.new_file().path().unwrap().to_str().unwrap();
                let mode = delta.new_file().mode();
                patch.push_str(&format!(" create mode {:o} {}\n", i32::from(mode), path));
            }
            Delta::Deleted => {
                let path = delta.old_file().path().unwrap().to_str().unwrap();
                let mode = delta.old_file().mode();
                patch.push_str(&format!(" delete mode {:o} {}\n", i32::from(mode), path));
            }
            _ => {} // TODO: handle other types of changes (e.g. modified, renamed, copied)
        }
    }
    patch.push_str("\n");

    diff.print(git2::DiffFormat::Patch, |_, _, line| {
        let origin = line.origin();
        match origin {
            ' ' | '+' | '-' => {
                patch.push(origin);
            }
            _ => (),
        };

        let Ok(content) = std::str::from_utf8(line.content()) else {
            return false;
        };
        patch.push_str(content);
        true
    })?;
    Ok(patch)
}

pub fn write_patch_to_file(
    parent: &Commit,
    commit: &Commit,
    repo: &Repository,
    path: &Path,
) -> anyhow::Result<()> {
    let patch = get_patch(parent, commit, repo)?;
    let mut file = OpenOptions::new()
        .write(true)
        .create(true)
        .truncate(true)
        .open(path)?;

    file.write_all(patch.as_bytes())?;
    Ok(())
}

fn git_time_to_chrono_datetime(
    time: git2::Time,
) -> anyhow::Result<chrono::DateTime<chrono::FixedOffset>> {
    let timestamp_secs = time.seconds();
    let offset_minutes = time.offset_minutes();
    let offset = chrono::FixedOffset::east_opt(offset_minutes * 60)
        .with_context(|| format!("Invalid timezone offset {} minutes", offset_minutes))?;
    let datetime = chrono::DateTime::from_timestamp_secs(timestamp_secs)
        .with_context(|| format!("Invalid timestamp_secs {}", timestamp_secs))?;
    let datetime = datetime.with_timezone(&offset);
    Ok(datetime)
}

pub struct PatchMetadata {
    pub author: SignatureData,
    pub committer: SignatureData,
    pub commit_message: String,
}
pub fn parse_patch_metadata(vec: &Vec<u8>) -> anyhow::Result<PatchMetadata> {
    let headers = std::str::from_utf8(vec)?
        .lines()
        .take_while(|line| !line.trim().is_empty());
    let headers = headers
        .map(|line| {
            let mut parts = line.splitn(2, ": ");
            let key = parts.next().unwrap();
            let value = parts.next().unwrap_or("");
            (key, value)
        })
        .collect::<HashMap<_, _>>();

    let author_sig = headers
        .get(X_GIT_PATCHER_AUTHOR)
        .with_context(|| format!("Missing {} header in patch", X_GIT_PATCHER_AUTHOR))?
        .parse::<SignatureData>()
        .with_context(|| format!("Failed to parse {} header in patch", X_GIT_PATCHER_AUTHOR))?;

    let committer_sig = headers
        .get(X_GIT_PATCHER_COMMITTER)
        .with_context(|| format!("Missing {} header in patch", X_GIT_PATCHER_COMMITTER))?
        .parse::<SignatureData>()
        .with_context(|| {
            format!(
                "Failed to parse {} header in patch",
                X_GIT_PATCHER_COMMITTER
            )
        })?;

    let commit_message = headers
        .get(X_GIT_PATCHER_COMMIT_MESSAGE)
        .with_context(|| format!("Missing {} header in patch", X_GIT_PATCHER_COMMIT_MESSAGE))?;
    let commit_message = BASE64_STANDARD.decode(commit_message).with_context(|| {
        format!(
            "Failed to decode base64 commit message in {} header",
            X_GIT_PATCHER_COMMIT_MESSAGE
        )
    })?;
    // TODO: avoid unnecessary UTF-8 conversion by directly using the bytes when creating the commit object in git2
    let commit_message = std::str::from_utf8(&commit_message)?.to_string();

    Ok(PatchMetadata {
        author: author_sig,
        committer: committer_sig,
        commit_message,
    })
}

const RE_NON_ALPHA: LazyLock<Regex> = LazyLock::new(|| Regex::new(r"[^a-zA-Z0-9]+").unwrap());
const RE_MULTIPLE_HYPHENS: LazyLock<Regex> = LazyLock::new(|| Regex::new(r"-+").unwrap());
pub fn generate_patch_name(commit: &Commit, index: usize, patch_count: usize) -> String {
    let title = commit.summary().unwrap_or("untitled");
    let mut slug = RE_NON_ALPHA.replace_all(title, "-").to_lowercase();
    slug = RE_MULTIPLE_HYPHENS.replace_all(&slug, "-").into_owned();
    let trimmed_slug = slug.trim_matches('-');
    let final_slug = if trimmed_slug.len() > 52 {
        &trimmed_slug[..52]
    } else {
        trimmed_slug
    }
    .trim_matches('-');

    let digits = patch_count.to_string().len().max(4);
    format!("{:0width$}-{}.patch", index + 1, final_slug, width = digits)
}
